/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLastfmCallbackImport } from './routes/auth.lastfm.callback'
import { Route as AuthDiscogsCallbackImport } from './routes/auth.discogs.callback'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLastfmCallbackRoute = AuthLastfmCallbackImport.update({
  id: '/auth/lastfm/callback',
  path: '/auth/lastfm/callback',
  getParentRoute: () => rootRoute,
} as any)

const AuthDiscogsCallbackRoute = AuthDiscogsCallbackImport.update({
  id: '/auth/discogs/callback',
  path: '/auth/discogs/callback',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/discogs/callback': {
      id: '/auth/discogs/callback'
      path: '/auth/discogs/callback'
      fullPath: '/auth/discogs/callback'
      preLoaderRoute: typeof AuthDiscogsCallbackImport
      parentRoute: typeof rootRoute
    }
    '/auth/lastfm/callback': {
      id: '/auth/lastfm/callback'
      path: '/auth/lastfm/callback'
      fullPath: '/auth/lastfm/callback'
      preLoaderRoute: typeof AuthLastfmCallbackImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/discogs/callback': typeof AuthDiscogsCallbackRoute
  '/auth/lastfm/callback': typeof AuthLastfmCallbackRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/discogs/callback': typeof AuthDiscogsCallbackRoute
  '/auth/lastfm/callback': typeof AuthLastfmCallbackRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/discogs/callback': typeof AuthDiscogsCallbackRoute
  '/auth/lastfm/callback': typeof AuthLastfmCallbackRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/discogs/callback' | '/auth/lastfm/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/discogs/callback' | '/auth/lastfm/callback'
  id: '__root__' | '/' | '/auth/discogs/callback' | '/auth/lastfm/callback'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthDiscogsCallbackRoute: typeof AuthDiscogsCallbackRoute
  AuthLastfmCallbackRoute: typeof AuthLastfmCallbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthDiscogsCallbackRoute: AuthDiscogsCallbackRoute,
  AuthLastfmCallbackRoute: AuthLastfmCallbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/discogs/callback",
        "/auth/lastfm/callback"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/discogs/callback": {
      "filePath": "auth.discogs.callback.tsx"
    },
    "/auth/lastfm/callback": {
      "filePath": "auth.lastfm.callback.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
