/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ScrobbleImport } from './routes/scrobble'
import { Route as IndexImport } from './routes/index'
import { Route as ReleaseIdImport } from './routes/release.$id'
import { Route as AuthLastfmCallbackImport } from './routes/auth.lastfm.callback'
import { Route as AuthDiscogsCallbackImport } from './routes/auth.discogs.callback'

// Create/Update Routes

const ScrobbleRoute = ScrobbleImport.update({
  id: '/scrobble',
  path: '/scrobble',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ReleaseIdRoute = ReleaseIdImport.update({
  id: '/release/$id',
  path: '/release/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuthLastfmCallbackRoute = AuthLastfmCallbackImport.update({
  id: '/auth/lastfm/callback',
  path: '/auth/lastfm/callback',
  getParentRoute: () => rootRoute,
} as any)

const AuthDiscogsCallbackRoute = AuthDiscogsCallbackImport.update({
  id: '/auth/discogs/callback',
  path: '/auth/discogs/callback',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/scrobble': {
      id: '/scrobble'
      path: '/scrobble'
      fullPath: '/scrobble'
      preLoaderRoute: typeof ScrobbleImport
      parentRoute: typeof rootRoute
    }
    '/release/$id': {
      id: '/release/$id'
      path: '/release/$id'
      fullPath: '/release/$id'
      preLoaderRoute: typeof ReleaseIdImport
      parentRoute: typeof rootRoute
    }
    '/auth/discogs/callback': {
      id: '/auth/discogs/callback'
      path: '/auth/discogs/callback'
      fullPath: '/auth/discogs/callback'
      preLoaderRoute: typeof AuthDiscogsCallbackImport
      parentRoute: typeof rootRoute
    }
    '/auth/lastfm/callback': {
      id: '/auth/lastfm/callback'
      path: '/auth/lastfm/callback'
      fullPath: '/auth/lastfm/callback'
      preLoaderRoute: typeof AuthLastfmCallbackImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scrobble': typeof ScrobbleRoute
  '/release/$id': typeof ReleaseIdRoute
  '/auth/discogs/callback': typeof AuthDiscogsCallbackRoute
  '/auth/lastfm/callback': typeof AuthLastfmCallbackRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scrobble': typeof ScrobbleRoute
  '/release/$id': typeof ReleaseIdRoute
  '/auth/discogs/callback': typeof AuthDiscogsCallbackRoute
  '/auth/lastfm/callback': typeof AuthLastfmCallbackRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/scrobble': typeof ScrobbleRoute
  '/release/$id': typeof ReleaseIdRoute
  '/auth/discogs/callback': typeof AuthDiscogsCallbackRoute
  '/auth/lastfm/callback': typeof AuthLastfmCallbackRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/scrobble'
    | '/release/$id'
    | '/auth/discogs/callback'
    | '/auth/lastfm/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/scrobble'
    | '/release/$id'
    | '/auth/discogs/callback'
    | '/auth/lastfm/callback'
  id:
    | '__root__'
    | '/'
    | '/scrobble'
    | '/release/$id'
    | '/auth/discogs/callback'
    | '/auth/lastfm/callback'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScrobbleRoute: typeof ScrobbleRoute
  ReleaseIdRoute: typeof ReleaseIdRoute
  AuthDiscogsCallbackRoute: typeof AuthDiscogsCallbackRoute
  AuthLastfmCallbackRoute: typeof AuthLastfmCallbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScrobbleRoute: ScrobbleRoute,
  ReleaseIdRoute: ReleaseIdRoute,
  AuthDiscogsCallbackRoute: AuthDiscogsCallbackRoute,
  AuthLastfmCallbackRoute: AuthLastfmCallbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/scrobble",
        "/release/$id",
        "/auth/discogs/callback",
        "/auth/lastfm/callback"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/scrobble": {
      "filePath": "scrobble.tsx"
    },
    "/release/$id": {
      "filePath": "release.$id.tsx"
    },
    "/auth/discogs/callback": {
      "filePath": "auth.discogs.callback.tsx"
    },
    "/auth/lastfm/callback": {
      "filePath": "auth.lastfm.callback.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
